// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8mk-k018xt0ahaaKw0GfpY9qmBzs68wg',
    appId: '1:486705346592:android:9bb1e14d90271158882445',
    messagingSenderId: '486705346592',
    projectId: 'we-chat-18f25',
    storageBucket: 'we-chat-18f25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCehrAeJhdjdZBPQEsH6HWmEcUw60j3IhY',
    appId: '1:486705346592:ios:7daf0e19c564d6d7882445',
    messagingSenderId: '486705346592',
    projectId: 'we-chat-18f25',
    storageBucket: 'we-chat-18f25.firebasestorage.app',
    androidClientId: '486705346592-lbg9sk6kos45lppjp7m4594dfeek436t.apps.googleusercontent.com',
    iosClientId: '486705346592-oos6b7csni6t4an41ohj0eardsh3ugid.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

}